---
title: "Comparing Returns for Clients"
author: "Daniel Egan"
date: 2018-12-24
output:
  html_document:
    theme: cosmo
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r echo=FALSE, message=F, warning=FALSE }
library(data.table)
library(ggplot2)
library(knitr)
library(betterviz)
library(scales)
library(dplyr)

load("data/comparing_returns_for_clients.RData")
```

# Distributions

```{r echo=FALSE, message=F, warning=FALSE, fig.width=12, fig.height=4  }
week_returns_diff_long_delta %>%
  ggplot(aes(x=return_cat_mp, y=counter)) + 
  geom_point(fill = adjustcolor("blue", alpha.f = 1), 
         col = adjustcolor("blue", alpha.f = 0.3), 
         size = 1/2
         ) + 
  geom_vline(xintercept = 0) + 
  xlab(paste0("Return difference (", primary_ticker, " - ", secondary_ticker,")")) + 
  scale_x_continuous(label = percent) + 
  ylab("Frequency")

```

# Distributions

```{r echo=FALSE, message=F, warning=FALSE, fig.width=12, fig.height=4  }
nobs <- nrow(week_returns_diff_long_delta)
square_size <- ceiling(sqrt(nobs))

week_returns_diff_long_delta %>%
  ungroup() %>%
  arrange(value) %>% 
  mutate(nob = 1:n() -1, 
         modulo = nob / square_size, 
         mod_y = floor(modulo), 
         mod_x = round((modulo - mod_y) * square_size,0)
         ) %>%
  ggplot(aes(x=mod_x, y=mod_y, col=return_cat_mp)) + 
  geom_point() + 
  scale_color_gradient2(low = "orange", 
                        mid = "grey", 
                        high = "blue", 
                        midpoint = 0, 
                        labels = percent) + 
  xlab(paste0("Return difference (", primary_ticker, " - ", secondary_ticker,")")) +
  labs(color = "Return size") +
  theme_minimal() + 
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), 
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
        

```